FROM python:3.12-slim

LABEL org.opencontainers.image.source https://github.com/beecave-homelab/sanitize-text

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml ./
COPY sanitize_text ./sanitize_text
COPY requirements.dev.txt ./

RUN pip install --upgrade pip \
    && pip install -r requirements.dev.txt

EXPOSE 8081

ENV FLASK_APP=sanitize_text.webui:create_app

CMD ["flask", "run", "--host=0.0.0.0", "--port=8081", "--reload", "--debugger"]
